Fix: undefined local variable or method `e'
The example of using timezones from the README
(https://github.com/icalendar/icalendar#example) was causing the
following error :

 NameError:
   undefined local variable or method `e' for #<Icalendar::Event:0x007fc94f7a35f8>

This appears to be a leftover from 6a5bd05c - where the Event was
previously passed around as `e`, it should now use implicit `self`.

This commit makes the code use the implicit self, and adds a test case
which catches this error, based upon the code in the README.